### Health Check
GET http://localhost:8080/api/v1/healthcheck

### List
GET http://localhost:8080/api/v1/notes

### Create
POST http://localhost:8080/api/v1/notes
content-type: application/json

{
    "title": "a note",
    "content": "here some reminder, mention @raditzlawliet",
    "is_published": true
}

### Read
GET http://localhost:8080/api/v1/notes/a476b9df-a278-40c0-971c-d99e8bc51942

### Update
PATCH http://localhost:8080/api/v1/notes/a476b9df-a278-40c0-971c-d99e8bc51942
content-type: application/json

{
    "content": "here some reminder, mention @raditzlawliet share and like"
}

### Delete
DELETE http://localhost:8080/api/v1/notes/a476b9df-a278-40c0-971c-d99e8bc51942

